"""
BillNyay — Judge Agent.

Evaluates the appeal letter generated by BarristerAgent against Auditor, Clinician,
and Regulatory outputs, generating a QA Scorecard.

P1-8 (audit finding, CONFIRMED against the actual code): every sub-score used to be a
hardcoded constant regardless of input — citation_consistency=85, logical_adequacy=90,
tone_professionalism=95, hallucination_risk=5, always — and factual_accuracy only
toggled between 70/90 by raw text LENGTH. denial_details/clinical_evidence/
regulatory_evidence were accepted as parameters and never read. The Judge claimed to
evaluate the letter against the evidence while never looking at either.

This rewrite replaces cosmetic scoring with deterministic checks against the actual
inputs wherever a check can be made honestly:
- factual_accuracy: do the case's own extracted denial facts (code, procedure, insurer
  reason, policy clause) actually appear in the letter? When no real facts were
  extracted (UNSPECIFIED_FIELD placeholders), this is disclosed as unverifiable rather
  than scored as if it were fine.
- citation_consistency: does every PMID/DOI-shaped string in the letter trace back to
  the clinical evidence actually supplied? (After P1-7, clinical_evidence should never
  carry a citation at all — a citation appearing in the letter with no matching
  evidence is now flagged, not assumed consistent.)
- structural adequacy (replaces "logical_adequacy" as a deterministic proxy — it is
  NOT a claim of evaluating logical reasoning, only letter structure): are the required
  sections (clinical justification, statutory grounds, formal demand) present?
- tone proxy (replaces "tone_professionalism" as a deterministic proxy — NOT an NLP
  tone judgment): is there a salutation, a closing, and no leftover template
  placeholder text (e.g. "[POLICYHOLDER NAME]", "TODO", "Lorem ipsum")?
- hallucination_risk: does the letter cite a DIFFERENT denial code or claimed-cited
  amount than the one actually supplied?

None of these checks is a substitute for a human legal/clinical reviewer, and this file
says so in `meta` rather than implying otherwise. Where a genuine check cannot be made
(no denial_details at all), the affected sub-score is capped and an issue is raised
rather than defaulting to a high number.
"""

import logging
import re
from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, model_validator

logger = logging.getLogger("BillNyay.JudgeAgent")
logger.setLevel(logging.INFO)

# Mirrors the placeholder text apps/api/.../billnyay.py substitutes when the Auditor
# could not extract real denial facts (UNSPECIFIED_FIELD). Duplicated as a literal
# rather than imported — packages/billnyay must not import from apps/api (architecture
# invariant: packages stay app-agnostic). A value containing this phrase is treated as
# "not actually available," not as a real fact to check the letter against.
_UNSPECIFIED_MARKER = "not specified"

_CITATION_PATTERN = re.compile(r"\bPMID:\s*\d+\b|\bDOI:\s*\S+\b", re.IGNORECASE)

_PLACEHOLDER_LEFTOVER_PATTERN = re.compile(
    r"\[[A-Z_ ]{3,}\]|\bTODO\b|\bLorem ipsum\b|\bXXXX+\b", re.IGNORECASE
)

_REQUIRED_SECTION_MARKERS = [
    re.compile(r"clinical justification|medical necessity", re.IGNORECASE),
    re.compile(r"statutory|regulatory|irdai", re.IGNORECASE),
    re.compile(r"demand|reversal|timeline|thirty|30.day", re.IGNORECASE),
]


class Issue(BaseModel):
    id: str
    severity: str = Field(..., description='"low" | "medium" | "high"')
    description: str
    suggested_fix: Optional[str] = None


class SubScores(BaseModel):
    factual_accuracy: int = Field(..., ge=0, le=100)
    citation_consistency: int = Field(..., ge=0, le=100)
    logical_adequacy: int = Field(..., ge=0, le=100)
    tone_professionalism: int = Field(..., ge=0, le=100)
    hallucination_risk: int = Field(..., ge=0, le=100)


class JudgeScorecard(BaseModel):
    overall_score: int
    status: str
    sub_scores: SubScores
    issues: List[Issue]
    confidence_estimate: float = Field(..., ge=0.0, le=1.0)
    meta: Optional[Dict[str, Any]] = None

    @model_validator(mode="before")
    def compute_overall(cls, values):
        if "overall_score" in values:
            return values
        subs = values.get("sub_scores")
        if not subs:
            return values
        v = subs if isinstance(subs, dict) else subs.model_dump()
        overall = int(
            (
                v["factual_accuracy"]
                + v["citation_consistency"]
                + v["logical_adequacy"]
                + v["tone_professionalism"]
                - v["hallucination_risk"]
            )
            / 4
        )
        values["overall_score"] = min(max(overall, 0), 100)
        values["status"] = "approve" if overall >= 80 else "needs_revision"
        return values


def _field(obj: Any, name: str, default: str = "") -> str:
    """Reads a field from either a StructuredDenial instance or a plain dict — several
    call sites pass either (see format_clinical_evidence in barrister.py for the same
    pattern)."""
    if obj is None:
        return default
    value = getattr(obj, name, None)
    if value is None and isinstance(obj, dict):
        value = obj.get(name)
    return value if isinstance(value, str) else default


def _is_available(value: str) -> bool:
    return bool(value) and _UNSPECIFIED_MARKER not in value.lower()


def _normalize(text: str) -> str:
    """Lowercases and strips punctuation so a fact-presence check tolerates the letter
    paraphrasing punctuation around an extracted fact (e.g. a trailing period becoming
    an em-dash) without tolerating an actually different fact — this is deliberately
    still an exact (normalized) substring match, not fuzzy matching, so it cannot be
    fooled by a superficially-similar-but-wrong fact."""
    return re.sub(r"[^\w\s]", "", text.lower())


def _score_factual_accuracy(letter: str, denial_details: Any) -> "tuple[int, List[Issue]]":
    """Checks whether the case's own extracted denial facts actually appear in the
    letter. This is a real, checkable property: a letter about THIS case should
    reference THIS case's denial code/procedure/reason, not generic boilerplate."""
    fields = {
        "denial code": _field(denial_details, "denial_code"),
        "denied procedure": _field(denial_details, "procedure_denied"),
        "insurer's reason": _field(denial_details, "insurer_reason_snippet"),
    }
    available = {k: v for k, v in fields.items() if _is_available(v)}

    if not available:
        # No real denial facts were ever extracted — the letter's factual accuracy
        # genuinely cannot be verified against anything. Disclosed as such, not scored
        # as if verification happened and passed.
        return 40, [
            Issue(
                id="FACT-0",
                severity="high",
                description="No extracted denial facts (code/procedure/reason) were available to verify "
                "this letter against — factual accuracy could not be checked, not confirmed.",
                suggested_fix="Re-run extraction on a document containing the actual denial letter, "
                "or manually verify the letter's claims before relying on it.",
            )
        ]

    letter_normalized = _normalize(letter or "")
    missing = [label for label, value in available.items() if _normalize(value) not in letter_normalized]

    if not missing:
        return 95, []

    issues = [
        Issue(
            id=f"FACT-{i + 1}",
            severity="medium",
            description=f"The letter does not reference the case's actual {label} — it may be generic "
            "boilerplate rather than grounded in this case's documents.",
            suggested_fix=f"Ensure the {label} extracted from the case's documents is stated in the letter.",
        )
        for i, label in enumerate(missing)
    ]
    score = max(30, 95 - 25 * len(missing))
    return score, issues


def _score_citation_consistency(letter: str, clinical_evidence: Any) -> "tuple[int, List[Issue]]":
    """After P1-7, clinical_evidence should never carry a pubmed_id/DOI at all — this
    system has no real literature-verification capability. A citation-shaped string
    appearing in the LETTER TEXT with no corresponding entry in the supplied evidence
    is therefore a real red flag: either the Barrister invented one despite
    instructions, or a citation survived from an unexpected code path."""
    letter_citations = set(_CITATION_PATTERN.findall(letter or ""))
    if not letter_citations:
        return 100, []

    supplied_citations = set()
    items = getattr(clinical_evidence, "root", clinical_evidence) or []
    for item in items:
        pmid = _field(item, "pubmed_id")
        if pmid:
            supplied_citations.add(pmid.lower())

    unsupported = {c for c in letter_citations if c.lower() not in supplied_citations}
    if not unsupported:
        return 100, []

    return 20, [
        Issue(
            id="CITE-1",
            severity="high",
            description=f"The letter contains citation-shaped text not present in the supplied clinical "
            f"evidence: {sorted(unsupported)}. This system has no literature-verification capability, "
            "so an unsupported citation in the final letter is a likely fabrication.",
            suggested_fix="Remove the citation or replace it with general clinical reasoning that does "
            "not claim a specific, unverified source.",
        )
    ]


def _score_structural_adequacy(letter: str) -> "tuple[int, List[Issue]]":
    """Deterministic PROXY for letter structure — explicitly not a claim of evaluating
    logical reasoning quality, which this system has no reliable way to check."""
    missing = [
        label
        for label, pattern in zip(
            ["clinical justification section", "statutory/regulatory grounds section", "formal demand/timeline section"],
            _REQUIRED_SECTION_MARKERS,
        )
        if not pattern.search(letter or "")
    ]
    if not missing:
        return 90, []
    score = max(30, 90 - 25 * len(missing))
    return score, [
        Issue(
            id=f"STRUCT-{i + 1}",
            severity="medium",
            description=f"The letter appears to be missing its {label}.",
            suggested_fix=f"Add a {label} to the letter.",
        )
        for i, label in enumerate(missing)
    ]


def _score_tone_proxy(letter: str) -> "tuple[int, List[Issue]]":
    """Deterministic PROXY for professionalism — checks structural hallmarks of a
    formal letter and the absence of leftover template placeholders. NOT an NLP tone
    judgment, which this system does not perform."""
    issues = []
    score = 90

    placeholder_matches = _PLACEHOLDER_LEFTOVER_PATTERN.findall(letter or "")
    if placeholder_matches:
        score -= 40
        issues.append(
            Issue(
                id="TONE-1",
                severity="high",
                description=f"The letter contains unfilled template placeholder text: {placeholder_matches}. "
                "This would be sent to a real insurer with obviously unfinished content.",
                suggested_fix="Fill in or remove every placeholder before this letter is used.",
            )
        )

    has_salutation = bool(re.search(r"dear sir|dear madam|to the|to:\s", letter or "", re.IGNORECASE))
    has_closing = bool(re.search(r"yours faithfully|yours sincerely|the insured", letter or "", re.IGNORECASE))
    if not (has_salutation and has_closing):
        score -= 15
        issues.append(
            Issue(
                id="TONE-2",
                severity="low",
                description="The letter is missing a formal salutation and/or closing.",
                suggested_fix="Add a formal salutation (e.g. 'Dear Sir/Madam') and closing (e.g. 'Yours faithfully').",
            )
        )

    return max(30, score), issues


def _score_hallucination_risk(letter: str, denial_details: Any) -> "tuple[int, List[Issue]]":
    """Checks for the most concrete, checkable form of hallucination this system can
    verify: the letter asserting a DIFFERENT denial code than the one actually
    extracted for this case."""
    actual_code = _field(denial_details, "denial_code")
    if not _is_available(actual_code):
        # Nothing to check against — same honesty principle as _score_factual_accuracy:
        # absence of evidence is not evidence of low risk.
        return 50, []

    mentioned_codes = set(re.findall(r"\bDEN-[A-Z0-9]+\b", letter or "", re.IGNORECASE))
    mismatched = {c for c in mentioned_codes if c.lower() != actual_code.lower()}

    if not mismatched:
        return 5, []

    return 70, [
        Issue(
            id="HALLUC-1",
            severity="high",
            description=f"The letter references denial code(s) {sorted(mismatched)}, which do not match "
            f"this case's actual extracted denial code '{actual_code}'.",
            suggested_fix="Verify the correct denial code is used throughout the letter.",
        )
    ]


def run_judge_agent(
    appeal_letter: str,
    denial_details: Any = None,
    clinical_evidence: Any = None,
    regulatory_evidence: Any = None,
    **kwargs,
) -> JudgeScorecard:
    """Evaluates the drafted appeal letter with deterministic checks against the actual
    upstream evidence — see module docstring for what is and is not verified."""
    logger.info("[Judge] Scoring drafted appeal letter...")

    text = appeal_letter or ""
    issues: List[Issue] = []

    if len(text) < 300:
        issues.append(
            Issue(
                id="ISSUE-1",
                severity="high",
                description="Appeal letter is suspiciously brief.",
                suggested_fix="Expand clinical and regulatory argument sections.",
            )
        )

    factual, factual_issues = _score_factual_accuracy(text, denial_details)
    citation, citation_issues = _score_citation_consistency(text, clinical_evidence)
    structural, structural_issues = _score_structural_adequacy(text)
    tone, tone_issues = _score_tone_proxy(text)
    hallucination, halluc_issues = _score_hallucination_risk(text, denial_details)

    issues.extend(factual_issues)
    issues.extend(citation_issues)
    issues.extend(structural_issues)
    issues.extend(tone_issues)
    issues.extend(halluc_issues)

    subs = SubScores(
        factual_accuracy=factual,
        citation_consistency=citation,
        logical_adequacy=structural,
        tone_professionalism=tone,
        hallucination_risk=hallucination,
    )

    # Confidence reflects how much was actually verifiable, not a fixed constant: with
    # no denial_details to check against, the Judge could not do most of its job, and
    # must not report the same confidence as a fully-checked letter.
    confidence = 0.85 if _is_available(_field(denial_details, "denial_code")) else 0.35

    scorecard = JudgeScorecard(
        sub_scores=subs,
        issues=issues,
        confidence_estimate=confidence,
        meta={
            "evaluated_at": datetime.utcnow().isoformat(),
            "version": "v2.0-deterministic",
            "method": "Deterministic checks against supplied evidence (fact presence, citation "
            "traceability, structural section/placeholder checks, denial-code consistency). "
            "logical_adequacy and tone_professionalism are structural proxies, not an NLP "
            "judgment of reasoning quality or tone — this system does not perform either.",
        },
    )

    logger.info(f"[Judge] Completed — Score: {scorecard.overall_score}, Status: {scorecard.status}")
    return scorecard
